spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  profiles:  ##环境配置
    active: dev
  #邮件服务
  mail:
    host: smtp.qq.com             #邮箱服务器地址
    username: apesing@qq.com         #用户名
    password: iumgbpjzkniybjgg    #密码
    default-encoding: UTF-8       #编码
    port: 465                     #端口
    #配置SSL访问
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  mvc:
    favicon:
      enabled: false
mail:
  fromMail:
    addr: apesing@qq.com         #以谁来发送邮件
  logMail:                       #日志发送地址
    addr: 815566704@qq.com
